### ISSUE TITLE
kobs User Interface

### ISSUE THREAD

**Issue by AkshayDubey29** [kobsio/kobs#198]
We are getting the below error:

Could not initialize clusters context
Unexpected token < in JSON at position 0

We are using kubeconfig as a provider. Can anyone help me what exactly I am missing in the helm chart:

https://github.com/kobsio/helm-repository/blob/main/kobs-0.7.3.tgz
```  config.yaml: |
    clusters:
      providers:
        - provider: kubeconfig
          kubeconfig:
            path: /kobs/.kube/config```

**Comment by ricoberger** [comment]
Hi @AkshayDubey29, thanks for trying kobs and reporting the issue 🙂

Your are right with version 0.7.3 of the Helm chart the kubeconfig provider doesn't work. I published a new version 0.8.0 of the Helm chart and an [example](https://kobs.io/installation/helm/#use-the-kubeconfig-provider) how the kubeconfig provider can be used with the Helm chart.

If you still have problems with the setup, please let me know.

**Comment by AkshayDubey29** [comment]
Let me try, will update you in short :)

**Comment by AkshayDubey29** [comment]
Hi @ricoberger It seems I am missing some configuration getting the below error in logs, is it because I am running kobs in internal company's network?:

![image](https://user-images.githubusercontent.com/14831408/140599244-14544618-149d-4dd1-b8e6-e14f7ca28b21.png)

**Comment by AkshayDubey29** [comment]
Hi @ricoberger Sorry for bugging you a lot but seems I am missing some configuration, I am still getting same error after adding kubeconfig.

I am seeing below message in log is it something relevant?

time="2021-11-06T07:44:09Z" level=warning msg="Could not find auth info." func=github.com/kobsio/kobs/pkg/api/clusters/provider/kubeconfig.GetClusters file="/kobs/pkg/api/clusters/provider/kubeconfig/kubeconfig.go:69" name=scus-dev-a5 package=clusters

**Comment by AkshayDubey29** [comment]
![image](https://user-images.githubusercontent.com/14831408/140602871-d53510de-be0f-414e-b750-7a9b79a2cb7b.png)

All the errors/warning are gone now, but still seeing the same error :(

**Comment by ricoberger** [comment]
Hi @AkshayDubey29,

- The `x509: certificate signed by unknown authority` error might be fixable by adding `insecure-skip-tls-verify` or by providing a proxy configuration (`proxy-url`) if this is required in your network.
- The `Could not find auth info.` error means that the `users` field for a cluster wasn't found in the loaded kubeconfig file.

From your last screenshot everything looks ok for me, so I'm not 100 percent sure what the current problem is. Maybe you can also set the log level to `trace` to get some more information.

**Comment by AkshayDubey29** [comment]
@ricoberger Unfortunately nothing is showing up in tracing :(
![image](https://user-images.githubusercontent.com/14831408/140640164-d832647d-6449-4cd9-bb59-f55b24689e74.png)

![image](https://user-images.githubusercontent.com/14831408/140640154-15540398-c067-466c-9217-f94d228df417.png)

**Comment by ricoberger** [comment]
Are your trying to access the dashboard via port-forwarding?

If this is the case you have to set `kobs.settings.development` to `true` in the Helm chart and you have to forward port `15219` for the web frontend and port `15220` for the api.

**Comment by AkshayDubey29** [comment]
No that's not the case I have to configure Cname and Vs for accessing the application. 
But post making development as false I started getting below error:

![image](https://user-images.githubusercontent.com/14831408/140724010-6b6efb81-5dc4-42a9-8b21-fddf5ba50365.png)

**Comment by ricoberger** [comment]
Currently I can not reproduce the error. Can you share your complete values file, which you used to install kobs?

**Comment by AkshayDubey29** [comment]
@ricoberger Please do find values.yaml below

```#Changes for query Gateway
istioConfig:
   enabled: true

gateway:
  enabled: true
  name: istio-sct-kobs-gateway
  secretName: "kobs.sct-tracing.scus-dev-a5.cluster.k8s.us.****.net"

virtualService:
  hosts:
    - "sct-kobs.scus-dev-a5.cluster.k8s.us.****.net"
  gateways:
    - "sct-tracing/istio-sct-kobs-gateway"
  httpsHosts:
    - "sct-https-kobs.scus-dev-a5.cluster.k8s.us.****.net"


global:
  # Omit the istio-sidecar-injector configmap when generate a
  # standalone gateway. Gateways may be created in namespaces other
  # than `istio-system` and we don't want to re-create the injector
  # configmap in those.
  omitSidecarInjectorConfigMap: true

  # Istio control plane namespace: This specifies where the Istio control
  # plane was installed earlier.  Modify this if you installed the control
  # plane in a different namespace than istio-system.
  istioNamespace: istio-system

  proxy:
    # Sets the destination Statsd in envoy (the value of the "--statsdUdpAddress" proxy argument
    # would be <host>:<port>).
    # Disabled by default.
    # The istio-statsd-prom-bridge is deprecated and should not be used moving forward.
    envoyStatsd:
      # If enabled is set to true, host and port must also be provided. Istio no longer provides a statsd collector.
      enabled: false
      host: # example: statsd-svc.istio-system
      port: # example: 9125
    clusterDomain: "cluster.local"

# Default values for kobs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.




kuberos:
  oidcClientURL: https://accounts.google.com
  # `oidcClientURL` is the endpoint that is used to quesry OIDC info
  oidcClientID: REDACTED.apps.googleusercontent.com
  # `oidcClientID` is typically a long alpha numeric string.
  #   For G Suite the 'REDACTED' part is about 45 alphanumeric characters
  oidcSecret: super-secret-value-here
  # `oidcSecret` is typically a long alpha numeric string.
  #   For G Suite it's about 25 alphanumeric characters
  #   For security reasons it's best to set this at deployment time with
  #     `--set kuberos.oidcSecret=mySuper-secretPassPhrase`
  clusters:
  # The clusters below must all use the same OIDC details above
  #   The config snippet that is generated for a user will default
  #   to the first cluster
  - name: scus-dev-a5
    # `name` is a label to apply to the cluster. It would normally be
    #   the fqdn of the cluster eg dev-cluster.example.com
    #   it can be something a little more friendly eg dev-cluster
    apiServer: https://kubernetes.default.svc:443
    # `apiServer` is the url for kubectl
    #   This is typically  https://api.fqdn
    caCrt: |-
      -----BEGIN CERTIFICATE-----
      ******=
      -----END CERTIFICATE-----
    # `caCrt` is the public / CA cert for the cluster

nameOverride: ""
fullnameOverride: ""

replicas: 1

## Specify a list of image pull secrets, to avoid the DockerHub rate limit or to pull the kobs/enovy image from a
## private registry.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
##
imagePullSecrets: []
  # - name: regcred

## Specify security settings for the created Pods. To set the security settings for the kobs or envoy Container use the
## corresponding "securityContext" field.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  fsGroup: 2000
  runAsUser: 1000

## Specify a map of key-value pairs, to assign the Pods to a specific set of nodes.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodeselector
##
nodeSelector: {}

## Specify the tolerations for the kobs Pods.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
##
tolerations: []

## Specify a node affinity or inter-pod affinity / anti-affinity for an advanced scheduling of the kobs Pods.
## See: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Specify all infromation for the kobs pods.
##
kobs:
  ## Set the image which should be used for kobs.
  ##
  image:
    repository: hub.docker.prod.*****.com/kobsio/kobs
    tag: v0.5.0
    pullPolicy: IfNotPresent

  ## Specify additional labels and annotations for the created Pods.
  ##
  annotations: {}
  labels: {}

  ## Specify security settings for the kobs Container. They override settings made at the Pod level via the
  ## "podSecurityContext" when there is overlap.
  ## See: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
  ##
  securityContext:
    runAsUser: 1000
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  ## We usually recommend not to specify default resources and to leave this as a conscious choice for the user. This
  ## also increases chances charts run on environments with little resources, such as Minikube. If you do want to
  ## specify resources, uncomment the following lines, adjust them as necessary, and remove the curly braces after
  ## 'resources:'.
  ##
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## Specify additional environment variables for the kobs container.
  ##
  env: []

  ## Specify some settings like log level, log format, etc. for kobs.
  ##
  settings:
    auth:
      enabled: false
      defaultTeam: "sct_devops"
      header: X-Auth-Request-Email
      interval: 1h0m0s
    clustersCacheDurationNamespaces: 5m
    logFormat: plain
    logLevel: info

  ## Set the content of the config.yaml file, which is used by kobs. The configuration file is used to specify the
  ## cluster providers and the configuration for the plugins.
  ##
  config: |
    clusters:
      providers:
        - provider: kubeconfig
          kubeconfig:
            path: /kobs/kubeconfig.yaml
  kubeconfig: |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: kubeconfig
    data:
      kubeconfig.yaml: |
        apiVersion: v1
        clusters:
        - cluster:
            certificate-authority-data: LS0tLS1C************o=
            server: https://master.scus-dev-a5.k8s.us.*****.net
          name: scus-dev-a5
        contexts:
        - context:
            cluster: scus-dev-a5
            user: ******@*****.******com/dex.oidc.prod.k8s.glb.us.*****.net
          name: scus-dev-a5
        current-context: scus-dev-a5
        kind: Config
        preferences: {}
        users:
        - name: jenkins
          user:
            token: eyJhb***************SBL-
## If you are using Istio you can create a VirtualService instead of an Ingress to expose kobs.
##
istio:
  ## Create a VirtualService, with the correct routes for the gRPC API and the React UI for kobs. You can provide a list
  ## of gateways and hosts for the VirtualService.
  ##
  virtualService:
    create: true

    gateways: 
      - "sct-tracing/istio-sct-kobs-gateway"
      # - gateway

    hosts: 
      - "kobs.scus-dev-a5.cluster.k8s.us.*****.net"
      # - chart-example.local

    timeout: 300s

    ## You can also add your own routes to the VirtualService. This can be used to add an oauth2-proxy to handle the
    ## authentication for the dashboard.
    ##
    additionalRoutes: []

## Specifies whether a service account should be created.
## See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  create: true

  ## Annotations to add to the service account
  ##
  annotations: {}

  ## The name of the service account to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name:

## Specifies whether a cluster role and cluster role binding should be created.
## The create cluster role and cluster role binding allows kobs read access to all resources.
## See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
##
rbac:
  create: true
  # The name of the cluster role and cluster role binding to use.
  # If not set and create is true, a name is generated using the fullname template.
  name:

## Set the type for the created service: ClusterIP, NodePort, LoadBalancer.
## See: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
##
service:
  type: ClusterIP

  annotations: {}
  labels: {}

## Create an Ingress to expose kobs.
## See: https://kubernetes.io/docs/concepts/services-networking/ingress/
##
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
    # - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Create a Service Monitor for the Prometheus Operator.
## See: https://github.com/coreos/prometheus-operator
##
serviceMonitor:
  enabled: false

  ## Interval at which metrics should be scraped. Fallback to the Prometheus default unless specified.
  ##
  # interval: 10s

  ## Timeout after which the scrape is ended. Fallback to the Prometheus default unless specified.
  ##
  # scrapeTimeout: 30s

  ## Additional labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
  ## See: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
  ##
  labels: {}

  ## HonorLabels chooses the metric's labels on collisions with target labels.
  ##
  honorLabels: true

  ## MetricRelabelConfigs to apply to samples before ingestion.
  ##
  metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

  ## RelabelConfigs to apply to samples before scraping. Prometheus Operator automatically adds relabelings for a few
  ## standard Kubernetes fields and replaces original scrape job name with __tmp_prometheus_job_name.
  ##
  relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace
```

**Comment by ricoberger** [comment]
Hi @AkshayDubey29, thanks for providing the values file. Did you made some modifications to the Helm chart or what is the `kobs.kubeconfig` key?

Some other things I saw:

- After the `Load Kubeconfig File.` log line there should be a `Context was found.` log line for each context from your provided kubeconfig file.
- There is currently a typo in one of the frontend files, which might lead to a wrong error message. Can you also check your browsers console (networking tab), which of the request produces the error message you see. Normally it should look like the following:

![Bildschirmfoto 2021-11-09 um 19 45 45](https://user-images.githubusercontent.com/18552168/140986538-502a1ce6-909b-470f-a11f-a127212791bf.png)

**Comment by AkshayDubey29** [comment]
@ricoberger 
kobs.kubeconfig is basically content of "/kobs/kubeconfig.yaml"

![image](https://user-images.githubusercontent.com/14831408/141046408-919d65be-8a23-4ede-8040-446cd95d4268.png)

**Comment by AkshayDubey29** [comment]
I think I am making mistake in kubeconfig, Can you help me with the users and access so that I can check with our infra team and get these certificates and all in place?

**Comment by AkshayDubey29** [comment]
Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by AkshayDubey29** [comment]
@ricoberger Tried from inside the container got below error:

/kobs $ wget http://kobs.sct-tracing.svc:15220/api/user
Connecting to kobs.sct-tracing.svc:15220 (10.50.207.171:15220)
wget: can't open 'user': Permission denied
/kobs $ wget http://kobs.sct-tracing.svc:15220/api/user

**Comment by AkshayDubey29** [comment]
Latest status:

![image](https://user-images.githubusercontent.com/14831408/141103180-b54b4025-147e-48af-a62c-8589634cb8fa.png)

**Comment by AkshayDubey29** [comment]
@ricoberger I think it is happening because of the text response:

Request
GET /api/user HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Host: sct-kobs.scus-dev-a5.cluster.k8s.us.******.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
Accept-Language: en-us
Referer: http://sct-kobs.scus-dev-a5.cluster.k8s.us.********.net/
Connection: keep-alive

Response
HTTP/1.1 200 OK
Date: Wed, 10 Nov 2021 12:40:18 GMT
Transfer-Encoding: Identity
**Content-Type: text/html; charset=utf-8**
Server: istio-envoy@scus-dev-a5
x-envoy-upstream-service-time: 0

**Comment by AkshayDubey29** [comment]
Awesome application is up now :)

**Comment by ricoberger** [comment]
Nice to hear 🙂
